version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.5-buster

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: "Restoring dependencies cache"
          keys:
          - v1-dependencies-{{ checksum "pyproject.toml" }}

      - run:
          name: install dependencies
          command: poetry install

      - save_cache:
          name: "Saving dependencies cache"
          key: v1-dependencies-{{ checksum "pyproject.toml" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - restore_cache:
          name: "Restoring hooks cache"
          key: v1-hooks-{{ checksum ".pre-commit-config.yaml" }}

      - run:
          name: linters
          command: SKIP=no-commit-to-branch poetry run pre-commit run -a -v

      - save_cache:
          name: "Saving hooks cache"
          paths:
            - "~/.cache/pre-commit/"
          key: v1-hooks-{{ checksum ".pre-commit-config.yaml" }}

      - run:
          name: run tests
          command: |
            poetry run pytest -vv -s --cov pactum --cov-report=html
            coveralls

      - store_artifacts:
          path: htmlcov
          destination: test-reports

branches:
  only:
    - master
